version: 1.0 
 
# SDKs used in the DevSpace environment 
SDKs: 
  NodeJS: "14.17.0" 
  Python: "3.9.6" 
  Java: "11.0.11" 
  Go: "1.16.3" 
 
# Runtimes defined in DevSpace (Docker or VMs) 
Runtimes: 
  Docker_Images: 
    - python: "3.9" 
    - node: "14" 
    - java: "11" 
  VMs: 
    - Ubuntu_20_04: "1.0" 
 
# Editors and their versions or configurations 
Editors: 
  VS_Code: 
    version: "1.58.0" 
    extensions: 
      - "ms-python.python" 
      - "esbenp.prettier-vscode" 
  PyCharm: 
    version: "2021.1" 
  IntelliJ: 
    version: "2021.2" 
 
# Project-specific configurations 
Projects: 
  Project_1: 
    sdk: "NodeJS" 
    dependencies: 
      - "npm_packages/package.json" 
      - "npm_packages/package-lock.json" 
  Project_2: 
    sdk: "Python" 
    dependencies: 
      - "pip_packages/requirements.txt" 
  Project_3: 
    sdk: "Java" 
    dependencies: 
      - "maven_dependencies/pom.xml" 
 
# Global Dependencies (npm, pip, maven) 
Dependencies: 
  npm: 
    version: "6.14.13" 
  pip: 
    version: "21.1.2" 
  maven: 
    version: "3.8.1" 
